---
new_page_extension: md
auto_deploy: true
admin_path: "/admin"
webhook_url: 
collections:
- path: posts
  label: Posts
  create: all
  permalink: "posts/:filename:"
- path: ''
  label: Pages
  create: all
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: true
file_template: ":year:/:month:/:day:/:filename:"
